<h1>
    <?php echo $this->getCompetitionTxt(); ?>
</h1>
<?php
$blockForm = $_SERVER['REQUEST_URI'];
$pos = strpos($blockForm, 'hide');
if($pos === false) :
?>
    <form class="form contact"
          action="<?= $block->escapeUrl($block->getValidationUrl()) ?>"
          id="competition-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}' >
        <fieldset class="fieldset">
            <div class="field firstname required">
                <label class="label" for="firstname"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
                <div class="control" id="controlFirstname">
                    <input name="firstname" id="firstname" title="<?= $block->escapeHtmlAttr(__('First name')) ?>" value="" class="input-text" type="text" data-validate="{required:true}" />
                </div>
            </div>
            <div class="field lastname required">
                <label class="label" for="lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
                <div class="control" id="controlLastname">
                    <input name="lastname" id="lastname" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required" id="controlEmail">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control" id="controlEmail">
                    <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" />
                </div>
            </div>
            <div class="field answer required" id="controlAnswer">
                <label class="label" for="answer"><span><?= $block->escapeHtml(__('What is the capital city of Belarus?')) ?></span></label>
                <div class="input-box">
                    <select name="answer" id="answer" data-validate="{required:true}">
                        <?php echo  $this->getDropdownOptions(); ?>
                    </select>
                </div>
            </div>
            <div class="field agree">
                <label class="label" for="agree"><span><?= $block->escapeHtml(__('Agree to term and conditions')) ?></span></label>
                <div class="input-box">
                    <input name="agree" id="agree" title="Agree to term and conditions" value="1" type="checkbox" />
                </div>
            </div>
            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
<?php endif; ?>